# Generated by Django 6.1.1 on 2026-09-09 11:34
import re

from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    """Give every pre-existing user (created before the Profile model
    existed) a nickname, so the nickname-login and friends-list features
    work for accounts that predate this feature.

    Nickname is derived from the local part of their username (usually an
    email address at this point in the app's history — see
    accounts/views.py:register), stripped down to the characters the
    nickname validator allows, with a numeric suffix added on collision.
    """
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')

    for user in User.objects.all():
        if Profile.objects.filter(user=user).exists():
            continue

        base = re.sub(r'[^\w-]', '', user.username.split('@')[0])[:30] or f'user{user.pk}'
        nickname = base
        suffix = 1
        while Profile.objects.filter(nickname__iexact=nickname).exists():
            suffix += 1
            nickname = f'{base}{suffix}'[:30]

        Profile.objects.create(user=user, nickname=nickname)


def noop_reverse(apps, schema_editor):
    # Nothing to undo: leaving auto-generated profiles in place on a
    # rollback is harmless, and deleting them would risk losing nicknames
    # a user has since started relying on to log in.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles, noop_reverse),
    ]
